### ISSUE TITLE
Warn user about expensive VPN transactions

### ISSUE THREAD

**Issue by valiant1x** [letheanVPN/lethean-gui#151]
Users have presented concerns about potential "scammy" nodes setting prices that lead to unexpectedly large transactions, especially on subsequent payments. This potential method of taking more funds than expected from non-discerning users would likely involve setting the subsequent payment minutes to the max (1440 minutes in current SDP). If a user only paid for 10 minutes initially but was then charged for 1440 minutes of service subsequently there may be an unexpected large payment.

Currently, subsequent payments do not prompt users for a wallet password or even confirm the transaction with the user, as long as the user is still connected to the proxy.

Proposed possible solutions:
1. Make subsequent payment duration more clear to client users. It is not displayed at all in the initial connection dialog.
2. Allow users to set max LTHN payment for VPN services

**Comment by pallas1** [comment]
Possibly make subsequent payment duration related to first payment. For example, if first payment is 10 minute, max is 3x so 30 minutes.
