### ISSUE TITLE
`make clean` does not clean CLI submodule

### ISSUE THREAD

**Issue by valiant1x** [letheanVPN/lethean-gui#159]
`make clean` should clean the submodule build dirs (build, lib, include). Alternatively, the GUI `./build.sh` script should rebuild all components of the daemon after the submodule is updated.

**Comment by pallas1** [comment]
Currently there's no Makefile for the gui, maybe we should create one? And add "clean" + the usual targets for compilation, by calling build.sh?
If that sounds hacky, the alternative could be running the libwallet compilation from build.sh always, and if it's not needed it would just exit quickly (provided the daemon build system is doing his homework about libwallet).
