### ISSUE TITLE
connection takes for ever 

### ISSUE THREAD

**Issue by mahdi-ln** [letheanVPN/lethean-gui#161]
This lasts for ever:
![Screenshot from 2019-03-24 11-46-42](https://user-images.githubusercontent.com/27496531/54895386-fadbef00-4edc-11e9-9c54-76e0083d07e0.png)
console message: 
`qrc:///pages/IntenseDashboard.qml:657: TypeError: Cannot call method 'getTime' of undefined`
OS: ubuntu 18

**Comment by valiant1x** [comment]
Is this when connecting to all providers or only certain ones? Is payment
made? Which OS is this running on (including version)?

+alfasoftpt can you add a timeout, or at least a soft timeout that notifies
the user after a set period of time that connection cannot be made?

**Comment by Mahdi321** [comment]
All providers 
No payment doesn't happen.
 OS: Ubuntu 18.04

**Comment by valiant1x** [comment]
fixed in #163 - however, a new release for Ubuntu and Mac is needed as we are currently only planning 4.0.0 for Windows.

**Comment by valiant1x** [comment]
Related #173 , although the above discusses only haproxy
