### ISSUE TITLE
Disconnect button does not disconnect VPN connection on Linux

### ISSUE THREAD

**Issue by ronnylov** [letheanVPN/lethean-gui#188]
When using the GUI wallet connecting with OpenVPN the connection to the VPN provider does not stop when pressing disconnect button. Only way I could make it stop was to reboot my computer or wait until payment period ends. When testing different providers it is annoying not being able to quickly disconnect.

(Using command line VPN client lthnvpnc instead works to disconnect by using a Ctrl-C so the issue seems to be within the GUI wallet)

**Comment by Mahdi321** [comment]
This happen in windows app, too (using proxy mode)
