### ISSUE TITLE
GTK rendering problems with some newer linux distributions

### ISSUE THREAD

**Issue by pallas1** [letheanVPN/lethean-gui#76]
A user reported issues trying to install the wallet to a freshly installed Lubuntu. He had to run 

`export QT_STYLE_OVERRIDE=gtk2`

in order to run it properly. I could not reproduce it, but we might have similar issues on other "light" distributions like xubuntu.

**Comment by konstantinakis** [comment]
lubuntu Version 18.04 in a VirtualBox
