### ISSUE TITLE
[LOW] Transitory wrong amount in history (until first block confirmation)

### ISSUE THREAD

**Issue by zib92130** [letheanVPN/lethean-gui#78]
Basically the amount is wrong (it includes fees), until the first confirmation. Then is it updated OK.
When doing the screenshot for the issue, another problem appears for the first time : the date/time of the payment was ... odd, but revert to correct value (like amount) on the first confirmation

A picture worth 1000 words...

![lthn_client_transitory_amount_bug](https://user-images.githubusercontent.com/19981031/45763987-fa168780-bc31-11e8-8b83-cd93ab60b95f.png)

**Comment by pallas1** [comment]
I could reproduce the first problem (fees included/not included) but not the second (weird timestamps).
May it be caused by some timezone setting or such on your machine? Which OS?

**Comment by zib92130** [comment]
Ubuntu 18; up to date. I didn't reproduce either after. Only happened while I was doing the test to take screenshots for the fee issue! 
That's Murphy's Law... what else?, Georges would say ! ;-)
For the timezone, this might be an hypothesis (machine is UTC+2  + ntp) , but I really don't explain how to achieve nearly 2 days back.  
```
$ timedatectl status
                      Local time: mar. 2018-09-25 16:11:59 CEST
                  Universal time: mar. 2018-09-25 14:11:59 UTC
                        RTC time: mar. 2018-09-25 14:12:00
                       Time zone: Europe/Paris (CEST, +0200)
       System clock synchronized: yes
systemd-timesyncd.service active: yes
                 RTC in local TZ: no
```
Not a big deal for now. Let's say it's a VM glitch in proxmox...
